### ISSUE TITLE
Shortcuts broken in Android 13

### ISSUE THREAD

**Issue by Grendel66** [butzist/ActivityLauncher#171] opened 2022-09-07 01:50 UTC
While activities launch fine out of the Activity Launcher app, created shortcuts just pop up an "App isn't installed." toast message in Android 13. Same behavior using Pixel or Nova launchers.

**Comment by ghoff** [comment] 2022-09-07 18:13
Lots of shortcuts still work.  An example of one that does not work for me on a Pixel 6 with Android 13 is System Update within Google Play services.  Launching the activity from within Activity Launcher works fine.  Trying to use a shortcut results in the mentioned error.

**Comment by drogga** [comment] 2022-09-17 09:26
As and if I understand correctly, you ve updated from 12 to 13 (huge mistake) and now you are complaining that the previously created activities shortcuts on A.12 no longer work on 13, well you cam blame Google and the manufacturer, because those are dynamic and can change any moment.

**Comment by heftig** [comment] 2022-09-23 10:28
No, even newly created shortcuts do not work.

Launching "Phone info" (`com.android.phone.settings.RadioInfo`) from Activity Launcher's activity works, but a shortcut created for it is broken.

**Comment by drogga** [comment] 2022-09-23 10:51
@heftig You mean it's created, but trying to launch the activity from it throws a toast message or something ?, if YES, please post the text from it here, you can grab it with the help of the Toast Source app, here's the link: https://play.google.com/store/apps/details?id=pl.revanmj.toastsource
...posting a screenshot of it is less useful, also make sure it's in English...

**Comment by heftig** [comment] 2022-09-23 11:43
It just says "App isn't installed."

**Comment by ghoff** [comment] 2022-09-23 13:19
Toast Source reports exactly "App isn't installed." and that Pixel Launcher generated the toast message. I'm sorry I was misleading about the shortcut.  My comment does very much imply that I was trying to use the shortcut I created under 12.  I deleted the  shortcut created under 12 and re-creating it under Android 13.  The new shortcut generates the error message.

@drogga  thank you for Activity Launcher.  It is a great utility.

**Comment by drogga** [comment] 2022-09-23 13:49
@heftig, @ghoff Can you please try any other app that can create shortcuts, in order to see if the problem is with A.L. only ?

**Comment by ghoff** [comment] 2022-09-24 00:04
I've created quite a few shortcuts and I'm not completely sure but the pattern seems to be that shortcuts created to pre-installed apps don't work but shortcuts to installed apps do work.  Directly launching from A. L. works for both.

**Comment by drogga** [comment] 2022-09-24 06:10
@ghoff I asked you to try with any other competitor / alternative "shortcut creator" app, for example go to /sdex/ActivityManager here on GitHub and try the same with his app, /MuntashirAkon/AppManager can create shortcuts too and plenty of so many other app on PlayStore, just pick one and report back how it went...

**Comment by ghoff** [comment] 2022-09-24 16:14
Trying to create a shortcut to phone info using an app called shortcut creator also generates an error "Could not open.  The app has been removed."

**Comment by drogga** [comment] 2022-09-26 18:04
@ghoff I guess you mean this: https://play.google.com/store/apps/details?id=com.alextern.shortcuthelper
...that app hasn't been updated since more than a year, back then there wasn't even A.12 (probably, didn't checked release dates), so try something that is updated in the last 3-4 months with fixes for A.13, I edited my previous post to make those clickable links, try those 2, if they don't work as it/they should, then the problem is entirely in A.13 and blame Google, because they make stupid decisions and mostly pointless changes, which they call "improvements" and "features" and constantly break stuff/things, which devs. have to fix because of them and sometimes it's impossible...

**Comment by jointfull** [comment] 2022-10-06 05:44
Hi. In the past month and a half, since I upgraded my Android from Android 12 to Android 13, I've been having the **exact same issues** as described by @Grendel66, @ghoff and @heftig.
I too have had a shortcut on my home screen that existed since before my upgrade which worked before the upgrade and have stopped working (toasting "App isn't installed.") after the upgrade.. and of course deleting the shortcut and creating it again (in Android 13) changed nothing (=still toasting the same error).
I would have thought that perhaps the problem was on my end, maybe in selecting an Activity or an App that do not support "shortcutting", but the same Activity/App works just fine when launched from within your app (i.e. selecting the ⋮ and then choosing "Launch activity").
The same problem exists not just for one specific Activity/App, but to numerous ones.. with no clear understanding which ones are supported and which ones are not (it's not the "installed before the upgrade" condition as @ghoff proposed).
I will give a couple of good examples and a couple of bad ("App isn't installed.") examples, so you can try to reproduce on your Android 13 test system:

Working properly App: [com.coffeebeanventures.easyvoicerecorder](https://play.google.com/store/apps/details?id=com.coffeebeanventures.easyvoicerecorder)
Working properly Activity: ru.irk.ang.balsan.shortcutled.MainActivity (for [ru.irk.ang.balsan.shortcutled](https://play.google.com/store/apps/details?id=ru.irk.ang.balsan.shortcutled))

Not working (toast) App: [com.dropbox.android](https://play.google.com/store/apps/details?id=com.dropbox.android)
Not working (toast) Activity: com.android.settings.Settings$PaymentSettingsActivity (for com.android.settings)

Adding some more examples in a screenshot:
<img src="https://user-images.githubusercontent.com/42198131/194222584-6bfcfb5c-68e0-42ca-b7ca-60e5620564f7.jpeg" height=500>

**Comment by drogga** [comment] 2022-10-06 08:47
BTW, I don't have access to A.13 in order to test, because I don't have the hardware resources to run it, that being for Android Studio's Emulator or WSA, maybe if there was a VMOS Rom for it, I could try to run it on SGS8+, but there isn't unfortunately, so my hands are tied and the owner or any of the known contributors are MIA.

**Comment by jointfull** [comment] 2022-10-07 06:27
> Try creating the same activities shortcuts with the 2 apps I linked above

I just tried both, and they both give the same error ("App isn't installed.") after the shortcut has been created.

**Comment by drogga** [comment] 2022-10-07 07:20
That sums it up then, the problem is with the OS itself, blame Google, because if the App Manager, which is being actively developed isn't able to create working ones, then nothing can.

**Comment by butzist** [comment] 2022-10-07 07:57
You can try the root mode of our app, is nothing else helps

**Comment by jointfull** [comment] 2022-10-07 08:39
> You can try the root mode of our app, if nothing else works

I tried that too, but it produces the exact same result.

**Comment by butzist** [comment] 2022-10-07 09:14
Then it's hopeless 😅

**Comment by jointfull** [comment] 2022-10-22 21:59
> That sums it up then, the problem is with the OS itself, blame Google, because if the App Manager, which is being actively developed isn't able to create working ones, then nothing can.

Well, that's entirely **not true**.
I just installef 3 other shortcut making applications from the store, and they all work flawlessly, while your app still doesn't.

Working alternatives:
- [rk.android.app.shortcutmaker](https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker) 
- [com.alextern.shortcuthelper](https://play.google.com/store/apps/details?id=com.alextern.shortcuthelper) 
- [com.sika524.android.quickshortcut](https://play.google.com/store/apps/details?id=com.sika524.android.quickshortcut) 

<img src="https://user-images.githubusercontent.com/42198131/197363764-92db06a6-6c19-4440-b3e6-40edddfeba90.jpg" height=200>

**Comment by jointfull** [comment] 2022-10-22 22:39
By the way, looking at the Manifest, I would argue that it has to do with the Action, which on you app (and on the 2 alternatives you proposed) is not editable from the UI, and I think you use a default (or missing) one instead of the one really needed for such complex apps (**MAIN** in this case).

I'm attaching the relevant Manifest section for this Activity:

```
    <activity
      android:label="@7F040E74"
      android:icon="@7F02036D"
      android:name="com.android.settings.Settings$PaymentSettingsActivity"
      android:exported="true">
      <intent-filter
        android:priority="1">
        <action
          android:name="android.settings.NFC_PAYMENT_SETTINGS">
        </action>
        <category
          android:name="android.intent.category.DEFAULT">
        </category>
      </intent-filter>
      <intent-filter>
        <action
          android:name="android.intent.action.MAIN">
        </action>
        <category
          android:name="android.intent.category.DEFAULT">
        </category>
      </intent-filter>
      <meta-data
        android:name="com.android.settings.FRAGMENT_CLASS"
        android:value="com.android.settings.nfc.PaymentSettings">
      </meta-data>
      <meta-data
        android:name="com.android.settings.HIGHLIGHT_MENU_KEY"
        android:value="@7F040D81">
      </meta-data>
      <meta-data
        android:name="com.android.settings.PRIMARY_PROFILE_CONTROLLED"
        android:value="true">
      </meta-data>
    </activity>
```

**Comment by jointfull** [comment] 2022-11-11 23:40
> Well, that's entirely **not true**. I just installed 3 other shortcut making applications from the store, and they all work flawlessly, while your app still doesn't.

Any update with this issue?

**Comment by Custnam** [comment] 2022-11-17 20:44
I've tried all the apps above and other shortcut creators and I always get app not installed. Guess it's 13s fault.

**Comment by drogga** [comment] 2022-11-18 12:05
Does stock A.13 (AOSP or Pixel) has \ allows creating settings shortcuts to Apps for example ?, on Samsung I don't have that option since years, in order to be able to create a shortcut for\to any of the Settings, I should use a shortcut creator, like this app and locate the activity for the thing I need, but that still won't be of use, if the activity is with abnormal state, like Private (\unexported\hidden) or Disabled, without Root (elevated permissions), only the Public and Enabled ones can be launched.

**Comment by Custnam** [comment] 2022-11-18 12:07
All shortcut creators worked up until A13. I read that Google intentionally
stopped it.

**Comment by drogga** [comment] 2022-11-18 12:25
@Custnam We know, read the other commitments here, Android 13 is garbage, 12 and 12L too, but not so much, 10 is the best (after 7), but 11 isn't bad too, given how worse 12\L\13 are and it will keep getting even worse, in a couple of months there will be A.14, which will be the worse yet (probably), and so on..., let's hope that Apple drops the stupid restrictions of iOS, the main one being the sideloading, which shouldn't need a developer's account and the installed apps shouldn't have any time limit, or whatever is thr case there.
If you want to be able to do anything useful with your Android emoji machine and you can't root, then you shouldn't updated to 13 and don't replace your device with any recent model of any brand, that ships with A.13.

**Comment by butzist** [comment] 2022-12-12 08:39
Should we unlist the app for Android 13 in Play Store?

**Comment by drogga** [comment] 2022-12-15 22:20
> Should we unlist the app for Android 13 in Play Store?

Probably not.

**Comment by zevix** [comment] 2022-12-23 20:21
I have the same problems since my Samsung updeated to a13. I use it to open cast settings

I have the same problems described above - "launch activity" works but the shortcut only says "app not installed"

I tried the first alternative from a few posts above and it works perfectly...

**Comment by butzist** [comment] 2022-12-30 07:22
The new release is pushed to the beta track and currently in review - will let you know when it's ready to test.

![image](https://user-images.githubusercontent.com/2405792/210044988-6f46d2a5-a357-4e31-acb2-472cd73a3d88.png)

**Comment by drogga** [comment] 2022-12-30 08:15
Are we waiting for the review on PS to pass before creating a new release here with a .apk attached\available ?, because there are artifacts yes, but they will eventually expire, also a account is usually needed in order to be able to DL them.
The latest with .apk available in the /releases is v1.9.2, no .apk(s) after that...
BTW, it would be better if they are properly named with the app name and the ver. (like: `Activity_Launcher_v1.14.5.apk`, or with spaces if that's ok here, maybe even the versionCode\build can be written), instead of all\most of them being with `ActivityLauncherApp-release.apk` file name.

**Comment by butzist** [comment] 2022-12-30 08:37
The beta release is available in Play Store now. The only "regression" that I see is that it shows a toast on starting a linked activity - personally I don't mind it and kinda consider it a feature 😉
Nevertheless, I expect users to complain about it - because having 1M users, there WILL be people who don't like any changes 😁. So what's your opinions on it? Should we remove the toast before release?

**Comment by Custnam** [comment] 2022-12-30 10:20
How do we get the latest? In app store it doesn't say update for me. Is there a beta program to sign up for? Thx

**Comment by butzist** [comment] 2022-12-30 10:36
Here's the link to sign up for beta: https://play.google.com/apps/testing/de.szalkowski.activitylauncher

**Comment by Custnam** [comment] 2022-12-30 10:57
The update showed up. After update I was able to launch previous shortcuts that said "no app installed". My main one being a shortcut to optimize battery use settings. Works perfect! Thanks for the hard work!

![Screenshot_20221230_025350_One UI Home](https://user-images.githubusercontent.com/118482804/210062782-3b05f7c2-2f28-42d1-968a-e59133b884f3.png)
![Screenshot_20221230_025342_Settings](https://user-images.githubusercontent.com/118482804/210062802-66449c24-f474-40c8-9bf1-ac254d84c51d.png)

**Comment by butzist** [comment] 2022-12-30 11:23
Thanks go to @Ismael034

**Comment by drogga** [comment] 2022-12-30 11:35
> So what's your opinions on it? Should we remove the toast before release?

Yes, because I mostly find it helpful (the toast) when it shows up when I launch a activity from within the app, but popping up for a shortcut too every time is being tapped/pressed on can quickly become annoying, for example I use the `Toast Source` app, which grabs and collects all the toast messages from everything, which will only fill the list with entries from the A.L.

**Comment by Custnam** [comment] 2022-12-30 12:09
Agree. Toast removed for shortcuts. Thx again

**Comment by drogga** [comment] 2022-12-31 09:23
@butzist do you intend to include the .apk in the releases assets?

**Comment by butzist** [comment] 2022-12-31 11:34
> @butzist do you intend to include the .apk in the releases assets? 

This is a separate topic. Closing this one as done.

@drogga you can download the artifact from the release build. Postponing this topic, due to too much effort, until I get a PR automating the release creation from the release build.

**Closed** 2022-12-31 11:34 UTC
