### ISSUE TITLE
Activities open with ActivityLauncher in back stack

### ISSUE THREAD

**Issue by lje** [butzist/ActivityLauncher#208] opened 2023-06-03 16:32 UTC
I have an Android 13 device. And since Nova Launcher's activity shortcuts no longer work ("App not installed" problem) I tried ActivityLauncher.
When I create a shortcut to an activity on my launcher, then open that activity by touching the shortcut and than press back, I will be in ActivityLauncher instead of being back to my launcher.
I assume ActivityLauncher should flag the opened activities with [FLAG_ACTIVITY_NEW_TASK](https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_NEW_TASK) to start them with an empty back stack.

**Comment by Terrance** [comment] 2023-09-09 09:40
I've been trying Activity Launcher out and I'm seeing the same issue, but from a quick look at the code it's already setting that flag for shortcuts:

https://github.com/butzist/ActivityLauncher/blob/ca0c2d3d0bb7fb2e04364508e8429b249c412669/ActivityLauncherApp/src/main/java/org/thirdparty/IconCreator.java#L47-L48

The embedded intent (`#Intent;launchFlags=0x14000000;component=...;end`) in the resulting shortcut appears to retain them, so I'm unsure why they aren't effective.

**Comment by lje** [comment] 2023-09-09 16:34
Workaround is to force-close ActivityLauncher after setting up your shortcuts, then the launched activities will not back-navigate to it.

**Comment by butzist** [comment] 2023-09-10 08:26
Since 1.14 we are creating all links to a proxy activity, that in turn starts the foreign one. Maybe that one is missing the flag? @lje you got some way to reproduce and test?

**Comment by lje** [comment] 2023-09-10 18:05
I have 1.14.6. with Nova Launcher. Nova can create activity shortcuts as well, but they have not adapted yet to Android 13 and proxy activities, which makes their shortcuts broken.

How to reproduce?

1. start ActivityLauncher
2. create any activity shortcut
3. switch to Nova and start the shortcut from launcher
4. navigate back from the activity you just started -> you will be in ActivityLauncher

1. force close ActivityLauncher
2. start the previously created shortcut from launcher
3. navigate back from the activity you just started -> you will be back in Nova / "Desktop"

1. start ActivityLauncher
2. switch to Nova and start the previously created shortcut from launcher
3. navigate back from the activity you just started -> you will be in ActivityLauncher

**Comment by youarenot667543** [comment] 2023-10-12 01:17
> I have an Android 13 device. And since Nova Launcher's activity shortcuts no longer work ("App not installed" problem) I tried ActivityLauncher.
> When I create a shortcut to an activity on my launcher, then open that activity by touching the shortcut and than press back, I will be in ActivityLauncher instead of being back to my launcher.
> I assume ActivityLauncher should flag the opened activities with [FLAG_ACTIVITY_NEW_TASK](https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_NEW_TASK) to start them with an empty back stack.
> 

- [ ]

**Comment by butzist** [comment] 2023-12-10 07:42
Feel free to create a PR

**Comment by butzist** [comment] 2024-03-24 15:32
Should be fixed in v2 - reopen if not

**Closed by butzist** 2024-03-24 15:32 UTC

**Comment by lje** [comment] 2024-03-26 12:33
> Should be fixed in v2 - reopen if not

Google Play (link from project's main page) still has the old version, last update was in December 2023. Is an update planned?

**Comment by butzist** [comment] 2024-03-26 14:20
You need to join the beta program

**Comment by Terrance** [comment] 2024-03-27 17:58
In 2.0.0 from F-Droid this seems to be working correctly now. 🙂

**Comment by butzist** [comment] 2024-03-27 18:12
Thanks for the confirmation ❤️
