### ISSUE TITLE
Can't find stirage

### ISSUE THREAD

**Issue by Vasilisxiros** [butzist/ActivityLauncher#112] opened 2022-01-07 20:13 UTC
For about two weeks now, when I start the program, the storage option appears locked and there is no access to the storage. XIAOMI MIUI global stable 12.0.2

![Screenshot_2022-01-07-10-42-01-216_de szalkowski activitylauncher](https://user-images.githubusercontent.com/97313685/148601568-813533e9-45fd-49c4-85e2-cf34f049f5be.jpg)

**Comment by butzist** [comment] 2022-01-08 08:48
Duplicate of https://github.com/butzist/ActivityLauncher/issues/109

**Closed by butzist** 2022-01-08 08:48 UTC
