### ISSUE TITLE
Can't create dual apps on Redmi 12S

### ISSUE THREAD

**Issue by Danivi82** [butzist/ActivityLauncher#226] opened 2023-12-11 12:59 UTC
Hi, the app keeps loading when try to duplicate apps in dual option in Redmi 12S. Is there an extra setting I have to do? Your help please thanks!

**Comment by drogga** [comment] 2023-12-13 10:46
Which app keeps loading ?, I doubt it's A.L., provide a video or I'm closing this, which doesn't mean that I won't close it after, since it doesn't sound like other than Redmi's problem...

**Comment by Danivi82** [comment] 2023-12-13 18:29
Activity loading and miui Downloader don't finish installing the dual apps. I tried from get apps and I found a dual space. It is not from xiaomi but it seems to work. If you know a native option I'd be relieved

**Closed** 2023-12-14 11:35 UTC

**Comment by drogga** [comment] 2023-12-14 11:45
So it's unrelated to this repo / app and you know it, but anyway decided despite that - hey let's bother some with my configuration problems/issues, because I didn't get a device (even an older one) from a reputable and decent brand, but buy a p.o.c one from a Chinese company (not that most aren't)...

**Comment by butzist** [comment] 2023-12-14 17:09
It seems like the issue is unrelated to this app. Please seek support from your device manufacturer instead.

**Comment by Danivi82** [comment] 2023-12-14 22:34
The issue is really related to native options redmin12S (because, my older redmi 9 had the native dual app option in the phone menu) and the possibility to solve the problem that don't allow to create dual apps even in a possible solution as apps from third party
