### ISSUE TITLE
messenger RCS flags

### ISSUE THREAD

**Issue by respok** [butzist/ActivityLauncher#22] opened 2019-10-31 13:53 UTC
I'm trying to set the OTP Pattern, but it does not want to Apply the only selection available when I come back to check the setting it doesn't get shown as applied.?

![Screenshot_20191031-093742](https://user-images.githubusercontent.com/23049332/67952304-7fa19080-fbc3-11e9-8750-c795a0a82c5e.png)
 

Sony Experia F8131
Google Messages beta
Android 8.0.0

**Comment by timjobutler** [comment] 2019-11-01 00:01
I have the same problem. The selection for the _ACS URL_ field is retained but the selection for _OTP Pattern_ field is cleared despite tapping the Apply button. Without having the selections for both fields retained, I cannot setup RCS chat in Google Messages.

**Comment by VaanAuron** [comment] 2019-11-01 04:33
I have somewhat the same problem but  for me when I put u in the 0TP pattern the apply button disappear and I can't apply it
![Screenshot_20191031-232215](https://user-images.githubusercontent.com/20316945/68002406-afd64700-fc36-11e9-84dc-5df18210f61c.png)
![Screenshot_20191031-232440](https://user-images.githubusercontent.com/20316945/68002416-bb297280-fc36-11e9-84e8-4b72b6e550f7.png)
 This my phone info  I hope I did everything right

**Comment by butzist** [comment] 2019-11-01 05:30
Hi there,

not sure how my app could influence the behaviour of this (third-party) settings screen. Activity Launcher can be used to start the settings screen - but the activity does not belong to my app.
Are there any parameters or dimensions that I can pass when starting the activity?

**Comment by timjobutler** [comment] 2019-11-01 05:49
@butzist Does that mean the _Apply_ button belongs to the Google Messages app

**Comment by butzist** [comment] 2019-11-01 12:16
@timjobutler Can you try to scroll down? Or use a Keyboard with arrow keys (eg USB/Bluetooth).

**Comment by butzist** [comment] 2019-11-01 12:19
@respok Today, I also tried to enable RCS and I experience the same behaviour ie URL saved but OTP pattern not saved - and RCS not working in Messaging App even after Force Quit. I'll try to ask the tutorial author on Reddit, whether this is expected.

**Comment by mmwhite8075** [comment] 2019-11-01 22:16
Hi. Looking for some help. Had RCS set up fine and now I can only send SMS, not receive. ATT, Note10+  Any help would be greatly appreciated.  I have done a factory data reset swaps in cards and still nothing.

**Comment by respok** [comment] 2019-11-02 12:42
under "Chat features" the"Status" it will say connected in green, and disconnected in red. my status says (green)connected so I guess it is working.

**Comment by mmwhite8075** [comment] 2019-11-02 12:46
I am unable to get anything I can't even get a verification text sent to
me. I think I may have broken something when trying to re install. I am
able to send text messages through the app but I am not able to receive
text messages whether RCS or simple SMS

**Comment by pmorrsn99** [comment] 2019-11-11 14:44
Ok I also cannot get the pattern to be applied, but my rcs works, but not for sending Group MMS, on my lg v30, however it does work from my nexus 6.

**Comment by jexhed** [comment] 2019-11-20 02:22
I have a similar problem, I can't scroll to the apply button once I set the OTP pattern. Seems to be problem with the app ?

**Comment by butzist** [comment] 2019-11-20 04:50
This is not related to activity launcher. But try to temporarily decrease the system font size.On 20 Nov 2019 03:22, jexhed <notifications@github.com> wrote:I have a similar problem, I can't scroll to the apply button once I set the OTP pattern. Seems to be problem with the app ?

**Comment by jexhed** [comment] 2019-11-20 05:40
Ok, reduced the font size and can now access the "Apply" button. When I click on "Apply" nothing happens and the OTP pattern change doesn't stick ?

**Comment by kairusds** [comment] 2019-11-24 00:48
this thread isn't an issue for the app bruh, try discussing this bug somewhere else also it works for me without setting the otp pattern so the problem is either your isp or device

**Comment by butzist** [comment] 2019-11-29 11:21
Closing issue as not related to app. If anyone runs into an issue with the RCS settings "apply" button:
* reduce system font size to make button visible
* "apply" button will not close the dialog nor will give any kind of feedback that settings have been applied
* "OTP pattern" will apply but the dialog will not display the change
* if RCS does not work try force-closing the messenger app
* if RCS still does not work then your device or ISP probably do not support RCS (e.g. Dual-Sim phones do not seem to support RCS)

**Closed by butzist** 2019-11-29 11:21 UTC
