### ISSUE TITLE
I cant find andtoid system webweaw in this app

### ISSUE THREAD

**Issue by PedPerformance** [butzist/ActivityLauncher#239] opened 2024-01-26 07:36 UTC
When i try to find ststem webweaw and its not showing but when i try tu find in other apps they show but not in this app

**Comment by drogga** [comment] 2024-01-26 11:25
Duplicate of #209

**Comment by drogga** [comment] 2024-01-26 11:30
@PedPerformance You wrote it wrong both times - in the subject/title and the test message below, please check your grammar first and report back.
Could it also be disabled ?

**Comment by drogga** [comment] 2024-01-26 11:34
@PedPerformance You wrote it wrong both times - in the subject/title and the text message below, please check your grammar first and report back.
Could it also be with a disabled state or don't have any activities, more particularly exported/public/enabled ones ?

**Closed** 2024-01-27 09:08 UTC
